---
# tasks file for check-net-config

- name: Including router config variables
  include_vars: interfaces_vars.yml

- name: Assigning the right router config to a generic var
  set_fact:
    router_if_desired: "{{ updated_key_item }}"
  vars:
    updated_key_item: "{{ item.value }}"
  with_dict: "{{ router_configs }}"
  when: "item.key is in ansible_nodename"

- name: Retrieving interfaces configuration
  set_fact:
    "{{ item }}={{ hostvars[inventory_hostname]['ansible_%s' | format(item)]['ipv4'] }}"
  with_items: "{{ ansible_interfaces }}"
  register: interfaces

- name: Building interfaces list
  set_fact:
    router_if_current: "{{ interfaces.results | map(attribute='ansible_facts') | list }}"

- name: Comparing required interface configuration with current one
  set_fact:
    if_compare: "{{ router_if_current | difference(router_if_desired) | list }}"

- name: Printing configuration mismatche(s)
  debug:
    msg:
      - "Interfaces configuration mismatche(s):"
      - "Current: {{ router_if_current | difference(router_if_desired) | list }}"
      - "Desired: {{ router_if_desired | difference(router_if_current) | list }}"
  when: "if_compare | length != 0"
  failed_when: "if_compare | length != 0"
