---
- name: Include tasks checking interface configuration
  include: "interfaces.yml"

- name: Include tasks checking route configuration
  include: "routes.yml"

- name: Include tasks checking nat configuration
  include: "nat.yml"
