---
# handlers file for config-router3

- name: ip ifdown-ifup
  shell: ifdown {{ item.item.device }}; ifup {{ item.item.device }}
  with_items: "{{ updated_device.results }}"
  when: item.changed

- name: route ifdown-ifup
  shell: ifdown {{ item.item.device }}; ifup {{ item.item.device }}
  with_items: "{{ device.results }}"
  when: item.changed
