---
vars:
  route:
    destination: "{{ item.destination }}"
    via: "{{ item.via }}"

keys:
  routes:
    value: "{{ route }}"
    # items: "^(?P<id>(([0-9]{1,3}\\.){3}[0-9]{1,3}(\\/([4-9]|[1-2][0-9]|3[0-2]))))\\svia\\s(?P<via>(([0-9]{1,3}\\.){3}[0-9]{1,3})).+"
    #items: "(?P<id>(([0-9]{1,3}\\.){3}[0-9]{1,3}(\\/([4-9]|[1-2][0-9]|3[0-2])))).+(?P<via>(([0-9]{1,3}\\.){3}[0-9]{1,3}))"
    items: "(?P<destination>([0-9]{1,3}\\.){3}[0-9]{1,3}(\\/([4-9]|[1-2][0-9]|3[0-2])))\\svia\\s(?P<via>([0-9]{1,3}\\.){3}[0-9]{1,3})"
